// <auto-generated />
using System;
using APIDesafio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIDesafio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220916193342_DatabaseAtt")]
    partial class DatabaseAtt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("APIDesafio.Models.Atendimento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DtAtendimento")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EsperaID")
                        .HasColumnType("int");

                    b.Property<int>("Mesa")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EsperaID");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("APIDesafio.Models.Espera", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DtEmissao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("StatusPainel")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TipoAtendimento")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Esperas");
                });

            modelBuilder.Entity("APIDesafio.Models.Atendimento", b =>
                {
                    b.HasOne("APIDesafio.Models.Espera", null)
                        .WithMany("atendimentos")
                        .HasForeignKey("EsperaID");
                });

            modelBuilder.Entity("APIDesafio.Models.Espera", b =>
                {
                    b.Navigation("atendimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
